### ISSUE TITLE
TemplateDoesNotExist issue when running demo

### ISSUE THREAD

**Issue by neodark** [thismatters/django-svelte-demo#1]
Thanks a lot for this example. To make it complete, could this be corrected so one doesn't fall into this issue when connecting to `http://localhost:8000/` with `make run` command:

```
TemplateDoesNotExist
home.html
```

**Comment by thismatters** [comment]
Yes, thank you for bringing this to my attention! I forgot to add a few files to the repo, the latest push should fix this.

Also be sure to check out the [video series of me expanding the demo on youtube](https://www.youtube.com/watch?v=ZQnUzoVTbpY&list=PLhkIGInQ4fIXiEH2uxMC1K79Xe7Rx1dVD)

Let me know if the latest push fixes your problem.

**Comment by neodark** [comment]
Wow! Thank you for your prompt reply and nice fix! :+1: 

The example page is very good now.

So we can close this issue:

https://github.com/thismatters/django-svelte-demo/commit/097f2da5e874329a9eb0970ff31a1bab6dc5f37c  Fixes #1
