### ISSUE TITLE
tried to update, failed :D

### ISSUE THREAD

**Issue by j2l** [thismatters/django-svelte-demo#5]
Great idea, even 4y later!
With Django==5.0.1, I have static paths not working for http://localhost:8000/static/AuthComponent.js and PostComponent.js
I used your django-svelte-template and demo to redo the client.

If by chance you update this project, please let me know :smile_cat:

**Comment by thismatters** [comment]
Oh, I'll have to try it with Django 5 and see what changes might interfere with operation. Thanks for the report!

**Comment by thismatters** [comment]
Hey @j2l I just tried this demo project with Django 5.0.1 and everything seemed to work. Could you go into more detail about your setup? Maybe we can figure out what went wrong.

**Comment by j2l** [comment]
Thank you @thismatters 
You're right, using the demo it works fine.
I don't remember all I did with your template at first.
Than you again for this gem.

**Comment by thismatters** [comment]
Glad you like it!
